### ISSUE TITLE
I2C hangs/freezing

### ISSUE THREAD

**Issue by stefschin** [enjoyneering/LiquidCrystal_I2C#1]
Hi,

Firstly, thank you a lot for this useful library. Nice work.
I have use a lot your library for different project, with good results.
But for my last project with relays, I have frequently freezing screen with STM32 Blue Pill.
And normal program still continues to work, so I think it coul be a loosing communication frame, so next comunication isn't understood by PCF8574 anymore.
Somebody with same problem? Any help will be thanksfull

**Comment by enjoyneering** [comment]
Does this happen immediately after or during a relay changeover?

**Comment by stefschin** [comment]
I can't measure it but it's inmediatly after a relay turning off, I think it's very noisy, but it's random. And microntroller continues working so I think it's a loosing frame communication between microcontroller and PCF8574 but I don't know how to check that and reset communication, did you?

**Comment by stefschin** [comment]
I remember that sometimes, when I was programming and testing without relays connected, I had this freezing too, I use a Machine state to change screen Menu and an interrupt TMR2 to make debounce and other functions

**Comment by enjoyneering** [comment]
The interrupting TMR2 can be a problem. Disable interrupts before I2C transactions and enable them after all transactions are completed.

**Comment by stefschin** [comment]
I need TMR2, because of counting, can I use TMR1 or 3 instead? or assign more priority to i2c interrupt?

**Comment by enjoyneering** [comment]
STM32F103C8T6 MCU aka Blue Pill has two I2C Interfaces namely I2C1 and I2C2
I2C1:
SDA – PB7 or PB9
SCL – PB6 or PB8

I2C2:
SDA – PB11
SCL – PB10

**TIM2**: PA1/PA2/PA3/PA15/PB3/PB5/**PB10**/**PB11**
**TIM4**: **PB6**/**PB7**/**PB8**/**PB9**


Use I2C1 insted I2C2.

**Comment by stefschin** [comment]
Ok, I will try! but I'm not using this pins for TMR2, is just software Interrupt but maybe it's a driver conflict. For LCD I use I2C1 with PB6 and 7
Thanks

**Comment by enjoyneering** [comment]
So did you try it?

**Comment by stefschin** [comment]
Not yet my friend, I will do it on weekend, I have too much work. I will notify you my tests

**Comment by max5555** [comment]
I don't know is it relevant but I have a problem with hangs during startup or just after flashing my ESP8266. Is there any way to send command to "restart" PCF8574?

**Comment by enjoyneering** [comment]
no responce. closed

**Comment by stefschin** [comment]
Sorry for delay, I could try it just a few weeks ago. I had same issue without relays, just with open IOs, so I discard noise problems. As we analyze it wasn't problem TMR with I2C conflict because I didn't use same pinout. So I analyze your code, not to deep because of my small knowlodge about C++, but I saw that you say that lcd.clear() "- command duration > 1.53 - 1.64ms" and you set a 2 ms delay. I use TMR2 interrupt each 1 ms. So I've try erasing this command and writing whole LCD again, instead of clearing and again printing. And it works now without this issue!!! 
I think that when you use `delay(LCD_HOME_CLEAR_DELAY);` some data is lost or I2C frame misses some bits when TMR interrupt enters. 
I like your library, I will check some others to see if it happens too and if they use delay, instead of checking millis or I2C INT. Thanks for your concern, I'm here to share my experience. Happy New Year!!!
