### ISSUE TITLE
Hang on start/reboot/flash

### ISSUE THREAD

**Issue by max5555** [enjoyneering/LiquidCrystal_I2C#2]
I have a problem with hangs during startup or just after flashing my ESP8266. Is there any way to send command to "restart" PCF8574?

The `lcd.begin(COLUMS, ROWS, LCD_5x8DOTS, D2, D1) != 1` but just after power cycle everything is OK. It is difficult to reproduce, but I have faced this problem three times on two different setups.

P.S. Maybe it is the same problem as https://github.com/enjoyneering/LiquidCrystal_I2C/issues/1

**Comment by enjoyneering** [comment]
This could be due to the very glitchy built-in I2C software driver in the Arduino ESP8266. Try to set Wire.setClockStretchLimit (2000); or even more right after lcd.begin()

**Comment by enjoyneering** [comment]
no response within 11 days. closed
