### ISSUE TITLE
Changes in last 1.3.1 version not working

### ISSUE THREAD

**Issue by stefschin** [enjoyneering/LiquidCrystal_I2C#6]
Hi, I'm using for a couple of years this library in a project write in platformio and stm32duino framework with a bluepill, and without the lcd.clear issue all the rest work good. I was using 1.2.4 version, now I want to update to last version 1.3.1 but it gives me this compiling errors:

![image](https://user-images.githubusercontent.com/32103938/210370574-8cb5bdf1-60ea-4b62-bdc4-3df373ab4044.png)

As I see in LiquidCrystal_I2C.cpp you add support for ESP32 and add a _VARIANT_ARDUINO_STM32_ but platformio isn't taking this option, is taking the last option: bool LiquidCrystal_I2C::begin() without any variables so we have the error about this 3 indentifiers.
I add the #define _VARIANT_ARDUINO_STM32_ in my main.c but isn't working anyway.

Maybe for platformio we have to add more definitions, somebody can help me?

**Comment by enjoyneering** [comment]
Thanks for the feedback. I think I fixed it. Can you check v1.3.2 and let me know?

**Comment by stefschin** [comment]
Thanks to look out but PlatformIO isn't updating the version, it still uses 1.3.1
![image](https://user-images.githubusercontent.com/32103938/211094710-248576a0-bc51-4af0-9583-3cd769090552.png)
Should I wait or load it manually?

**Comment by stefschin** [comment]
I replaced manually and still says 1.3.1 but it compiles with success!!! Thanks

**Comment by enjoyneering** [comment]
awesome. closed.

**Comment by stefschin** [comment]
Sorry but I didn't could run LCD with last changes, I thought that it was my mistake with the begin.lcd but I changed to the last STM32 example and isn't beginning, just the message through serial port:

![image](https://user-images.githubusercontent.com/32103938/215199428-c59c947e-7c89-48ec-b4b5-691f8dca5f84.png)

And when compiling I have this versions:

![image](https://user-images.githubusercontent.com/32103938/215199168-3241bba2-b7b9-42aa-8446-c40b3b953441.png)

Can you check the code please? I change library to version 1.2.4 and my code works great
