### ISSUE TITLE
last version 1.3.2 not working

### ISSUE THREAD

**Issue by stefschin** [enjoyneering/LiquidCrystal_I2C#7]
Sorry but I didn't could run LCD with last changes, I thought that it was my mistake with the begin.lcd but I changed to the last STM32 example and isn't beginning, just the message through serial port:

![image](https://user-images.githubusercontent.com/32103938/216427156-8904085b-c390-4cce-8e92-edbeea4082f9.png)

And when compiling I have this versions:

![image](https://user-images.githubusercontent.com/32103938/216427189-00a551fb-e2ae-41b2-8b42-3c7551649541.png)

Can you check the code please? I change library to version 1.2.4 and my code works great

**Comment by stefschin** [comment]
Sorry but I didn't could run LCD with last changes, I thought that it was my mistake with the begin.lcd but I changed to the last STM32 example and isn't beginning, just the message through serial port:

image

And when compiling I have this versions:

image

Can you check the code please? I change library to version 1.2.4 and my code works great

**Comment by enjoyneering** [comment]
Hi,

Make sure your LCD connected to SDA = PB9 and SCL = PB8. Try to reduce speed to 100000Hz

```
while (lcd.begin(COLUMS, ROWS, LCD_5x8DOTS, PB9, PB8, 100000) != 1) //colums, rows, characters size, SDA, SCL, I2C speed in Hz
```

**Comment by stefschin** [comment]
My LCD is connected to PB7 and PB6, I try with:

`while (lcd.begin(COLUMS, ROWS, LCD_5x8DOTS, PB7, PB6, 100000) != 1)`

but without success

**Comment by enjoyneering** [comment]
try 1.3.3. fixed & tested on BluePill F130C8

**Comment by enjoyneering** [comment]
thank you for feedback

**Comment by stefschin** [comment]
It's working great like usual, thanks to you! I tested 1.2.4 version with Black pill too, and work fine, I will let you know with this version. I have to build the setup, cheers

**Comment by enjoyneering** [comment]
The v1.3.x are faster than v1.2.4, uses less RAM and flash. Now that we fix all the problems with STM32 I suggest you upgrade to v1.3.3.

**Comment by stefschin** [comment]
I will do it, thanks, I will let you know when I try the library with Black Pill

**Comment by enjoyneering** [comment]
Hi,

Did you try Black Pill? The I2C pins should be the same - PB7 and PB6

**Comment by stefschin** [comment]
Hi, sorry for delay, it works with Back Pill 401 too! thanks
